# Generated by Django 3.2.4 on 2021-06-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20210606_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='type',
            field=models.CharField(default=1, max_length=50, verbose_name='Тип задачи'),
            preserve_default=False,
        ),
    ]
