# Generated by Django 3.2.4 on 2021-06-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_todo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='legends',
            name='text',
            field=models.CharField(default=1, max_length=500, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
