# Generated by Django 3.2.4 on 2021-06-06 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_legends_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legends',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='legid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.legends'),
        ),
    ]
